### ISSUE TITLE
記事メタデータに不備がある状態で `list:articles` を実行すると長大なエラーが出力される

### ISSUE THREAD

**Issue by sankantsu** [zenn-dev/zenn-editor#515]
### zenn-cli のバージョン

0.1.158

### 概要

記事のメタデータ (タイトル等) に yaml の文法上の不備がある場合に非常に長大なエラーが出力されます。

### 期待する状態

ユーザー体験の観点から、エラーメッセージを簡潔に表示できると望ましいと考えます。
また、特定の記事にエラーがあっても warning レベルのメッセージを出力して継続し、メタデータに不備が無い記事は通常通り一覧として表示されるとより嬉しいです。

### 例:

以下の例では、記事のうちのひとつのメタデータで `topics` のリスト末尾の `[` が抜けていて、yaml として無効な状態になっています。

```
---
title: "Neovim の LSP を設定するための基本知識"
emoji: "⚙️"
type: "tech"
topics: ["Neovim", "LSP"
published: true
published_at: 2023-12-11
publication_name: vim_jp
---

```

この状態で、`npx zenn list:articles` を実行したとき、以下のように非常に長大なエラーが出力されます。

```
~/blog/zenn% npx zenn list:articles 2>&1 | wc -c
 2813909
```

```
(node:16692) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js
 is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16714) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative i
nstead.
(Use `node --trace-deprecation ...` to show where the warning was created)

/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3
(()=>{var __webpack_modules__={44900:(e,t)=>{"use strict";function n(e,t,n){var a,r=t,i={ok:!1,pos:t,value:""};for(
a=e.charCodeAt(t);t<n&&a>=48&&a<=57||37===a;)a=e.charCodeAt(++t);return i.ok=!0,i.pos=t,i.value=e.slice(r,t),i}Obje
ct.defineProperty(t,"__esModule",{value:!0}),t.parseImageSize=void 0,t.parseImageSize=function(e,t,a){var r=e.charC
odeAt(t),i={ok:!1,pos:0,width:"",height:""};if(t>=a)return i;if(61!==r)return i;if(t++,120!==(r=e.charCodeAt(t))&&(
r<48||r>57))return i;var s=n(e,t,a);if(t=s.pos,120!==(r=e.charCodeAt(t)))return i;var o=n(e,++t,a);return t=o.pos,i
.width=s.value,i.height=o.value,i.pos=t,i.ok=!0,i}},57405:(e,t,n)=>{"use strict";Object.defineProperty(t,"__esModul
e",{value:!0});var a=n(44900);t.default=function(e){e.inline.ruler.before("emphasis","image",function(e){return fun
ction(t,n){var r,i,s,o,l,c,p,u,d,m,h,f,g="",E="",b="",_=t.pos,D=t.posMax;if(33!==t.src.charCodeAt(t.pos))return!1;i
f(91!==t.src.charCodeAt(t.pos+1))return!1;if(l=t.pos+2,(o=e.helpers.parseLinkLabel(t,t.pos+1,!1))<0)return!1;if((c=
o+1)<D&&40===t.src.charCodeAt(c)){for(c++;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(c>=D)return!1;for(f=c
,(u=e.helpers.parseLinkDestination(t.src,c,t.posMax)).ok&&(b=t.md.normalizeLink(u.str),t.md.validateLink(b)?c=u.pos
:b=""),f=c;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(u=e.helpers.parseLinkTitle(t.src,c,t.posMax),c<D&&f!
==c&&u.ok)for(d=u.str,c=u.pos;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);else d="";if(c-1>=0&&32===(i=t.src.c
harCodeAt(c-1))&&(u=a.parseImageSize(t.src,c,t.posMax)).ok)for(g=u.width,E=u.height,c=u.pos;c<D&&(32===(i=t.src.cha
rCodeAt(c))||10===i);c++);if(c>=D||41!==t.src.charCodeAt(c))return t.pos=_,!1;c++}else{if(void 0===t.env.references
)return!1;for(;c<D&&(32===(i=t.src.charCodeAt(c))||10===i);c++);if(c<D&&91===t.src.charCodeAt(c)?(f=c+1,(c=e.helper
s.parseLinkLabel(t,c))>=0?s=t.src.slice(f,c++):c=o+1):c=o+1,s||(s=t.src.slice(l,o)),!(p=t.env.references[e.utils.no
rmalizeReference(s)]))return t.pos=_,!1;b=p.href,d=p.title}if(!n){t.pos=l,t.posMax=o;var v=new t.md.inline.State(t.
src.slice(l,o),t.md,t.env,h=[]);v.md.inline.tokenize(v),(m=t.push("image","img",0)).attrs=r=[["src",b],["alt",""]],
(略)
YAMLException: missed comma between flow collection entries (6:1)

 3 | emoji: "⚙️"
 4 | type: "tech"
 5 | topics: ["Neovim", "LSP"
 6 | published: true
-----^
 7 | published_at: 2023-12-11
 8 | publication_name: vim_jp
    at Du (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2600423)
    at vu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2600458)
    at /Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2608417
    at Lu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2609013)
    at /Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2607611
    at Lu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2607935)
    at Pu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2615303)
    at Fu (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2616047)
    at Object.load (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2616272)
    at Object.yaml [as parse] (/Users/godai/blog/zenn/node_modules/zenn-cli/dist/server/zenn.js:3:2626261) {
  reason: 'missed comma between flow collection entries',
  mark: {
    name: null,
    buffer: '\n' +
      'title: "Neovim の LSP を設定するための基本知識"\n' +
      'emoji: "⚙️"\n' +
      'type: "tech"\n' +
      'topics: ["Neovim", "LSP"\n' +
      'published: true\n' +
      'published_at: 2023-12-11\n' +
      'publication_name: vim_jp\n',
    position: 86,
    line: 5,
    column: 0,
    snippet: ' 3 | emoji: "⚙️"\n' +
      ' 4 | type: "tech"\n' +
      ' 5 | topics: ["Neovim", "LSP"\n' +
      ' 6 | published: true\n' +
      '-----^\n' +
      ' 7 | published_at: 2023-12-11\n' +
      ' 8 | publication_name: vim_jp'
  }
}

Node.js v23.1.0
```

**Comment by sankantsu** [comment]
すみません、[Contribution](https://zenn-dev.github.io/zenn-docs-for-developers/contribution#issue-%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B) の以下の内容を見落としていました。

> あなたが機能リクエストやバグ報告をする場合は、どのツールやライブラリに対する内容であっても zenn/zenn-community リポジトリに Issue を作成してください。

[zenn-community](https://github.com/zenn-dev/zenn-community) に issue を移動させます。
